[package]
name = "neutrino-store-sqlite"
version = "0.1.0"
edition = "2024"

[dependencies]
deadpool-sqlite = { version = "0.13.0", features = ["bundled"] }

async-trait.workspace = true
ruma.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true

neutrino-store = { path = "../neutrino-store" }
