[package]
name = "neutrino-event"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
base64 = "0.22.1"
ruma = { workspace = true, features = ["events"] }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true

[dev-dependencies]
proptest.workspace = true
