[package]
name = "neutrino-main"
version = "0.1.0"
edition = "2024"

[features]
multi-user-shim = ["neutrino-http/multi-user-shim"]

[dependencies]
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

neutrino-common = { path = "../neutrino-common" }
neutrino-http = { path = "../neutrino-http" }

[target.'cfg(target_os = "android")'.dependencies]
paranoid-android = "0.2.2"
