[package]
name = "neutrino-room"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
ruma.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

neutrino-event = { path = "../neutrino-event" }

[dev-dependencies]
proptest.workspace = true
